district_id: "310100"
sender: "xxx@qq.com"
receiver: "xxx@qq.com"
username: "xxx@qq.com"
pop_token: "xxxxj"
do_job_time: "17:46"
ak_token: "xxx"
tianxing_token: "xxx"
fall_in_love_day: "2022-10-22"
birthday_day: "1998-01-20"
