district_id: "310100"
sender: "1037719686@qq.com"
receiver: "1037719686@qq.com"
username: "1037719686@qq.com"
pop_token: "gzeazwenrropbbbj"
do_job_time: "17:46"
ak_token: "SWfxLGcY5dimICZWaCTMiOe1Ozbez2GR"
tianxing_token: "75c83b5a6d54902a2f5ce97dfeb13d3b"
fall_in_love_day: "2022-10-22"
birthday_day: "1998-01-20"